In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(type(arr1))
print(arr1.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [6]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [7]:
arrN = np.array([1,2,3,4], ndmin=10)
print(arrN)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [ ]:
lst = []

upper = int(input("Enter the upper value + 1: "))

for i in range (1, upper):
    val = int(input("Enter value: "))
    lst.append(val)

print(np.array(lst))

[1 2 3 4 5]
