In [1]:
import numpy as np

In [4]:
# array filled with all 0's

arr0 = np.zeros(4)
print(arr0)

print()

arr0_1 = np.zeros((4,4))
print(arr0_1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# array filled with all 1's

arr1 = np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# empty array -- memory may already contain old data from previous programs.

arr_empty = np.empty(4)
print(arr_empty)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56595733e-307]


In [11]:
# array within a range

arr_range = np.arange(4)
print(arr_range)

[0 1 2 3]


In [12]:
# identity matrix

arr_identity = np.eye(3)
print(arr_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# array in which values are linearly spaced in a specif interval

arr_lin = np.linspace(0, 10, 3)
print(arr_lin)

[ 0.  5. 10.]
