In [1]:
import numpy as np

### rand(): random values between 0 & 1

In [4]:
np.random.rand(4,3)

array([[0.92070174, 0.13015002, 0.22457482],
       [0.87018424, 0.4072937 , 0.70448605],
       [0.75952305, 0.01634678, 0.80075699],
       [0.97604408, 0.11929242, 0.98836835]])

### randn() --- close to 0 values, maybe +ve, -ve as well

In [5]:
np.random.randn(4,3)

array([[ 0.49228328,  1.04778521,  0.15875462],
       [ 0.84932578,  1.19381719, -0.39697628],
       [-1.31858163, -0.93433701,  1.18927164],
       [ 1.08137057, -0.1356449 ,  0.08915782]])

### ranf() --- [0.0, 1.0)

In [7]:
np.random.ranf((4,3))

array([[0.7928291 , 0.7941756 , 0.89217479],
       [0.9394389 , 0.87518083, 0.17199838],
       [0.02834547, 0.85783919, 0.77823794],
       [0.31307229, 0.67163885, 0.40908139]])

### randint(start, end, how_many)

In [8]:
np.random.randint(4,50,7)

array([32, 32,  6, 17, 33,  7, 10], dtype=int32)