### a+b -> np.add(a, b)
### a-b -> np.subtract(a, b)
### a*b -> np.multipy(a, b)
### a/b -> np.divdide(a, b)
### a%b -> np.mod(a, b)
### a**b -> np.power(a, b)
### 1/a -> np.reciprocal(a, b)

#### can perform these operations manually as well

In [3]:
import numpy as np

In [4]:
a = [[10, 2, 8, 15],
     [3, 12, 1, 5]]

b = [[1,2,3,4],
     [1,2,3,4]]

In [5]:
print(np.add(a,b))

[[11  4 11 19]
 [ 4 14  4  9]]


In [6]:
print(np.subtract(a,b))

[[ 9  0  5 11]
 [ 2 10 -2  1]]


In [7]:
print(np.multiply(a,b))

[[10  4 24 60]
 [ 3 24  3 20]]


In [8]:
print(np.divide(a,b))

[[10.          1.          2.66666667  3.75      ]
 [ 3.          6.          0.33333333  1.25      ]]


In [9]:
print(np.mod(a,b))

[[0 0 2 3]
 [0 0 1 1]]


In [10]:
print(np.power(a,b))

[[   10     4   512 50625]
 [    3   144     1   625]]


In [12]:
print(np.reciprocal(a))

[[0 0 0 0]
 [0 0 1 0]]
