### np.min(x)
### np.max(x)
### np.argmin(x)/np.argmax(x) -- returns the index of minimum/maximum element
### np.sqrt(x)
### np.sin(x)
### np.cos(x)
### np.cumsum(x) -- works like prefix sum logic of cpp

### in 2d array -- axis = 0 --> along column, axis = 1 --> along row

In [1]:
import numpy as np

In [4]:
x = [1, 2, 3, 4, 5]
print(np.min(x), np.argmin(x))
print(np.max(x), np.argmax(x))
print(np.sqrt(x))
print(np.sin(x))
print(np.cos(x))
print(np.cumsum(x))

1 0
5 4
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1  3  6 10 15]


In [11]:
x = [[1,6,3,8],
     [5,2,7,4]]

print(np.min(x, axis=1))
print(np.min(x, axis=0))
print()
print(np.max(x, axis=1))
print(np.max(x, axis=0))

[1 2]
[1 2 3 4]

[8 7]
[5 6 7 8]
