In [3]:
import numpy as np

### Shape

In [5]:
var = np.array([[2,3],[2,3]])

print(var)
print(var.shape)

[[2 3]
 [2 3]]
(2, 2)


In [7]:
var1 = np.array([1,2,3,4], ndmin=5)

print(var1)
print(var1.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


### Reshape

In [16]:
var2 = np.array([1,2,3,4,5,6])
print(var2.ndim)
print(var2.shape)

print()

x = var2.reshape(3, 2)
print(x)
print(x.ndim)
print(x.shape)

1
(6,)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [17]:
one = var2.reshape(-1)
print(one)
print(one.ndim)
print(one.shape)

[1 2 3 4 5 6]
1
(6,)
