In [1]:
import numpy as np

### Rule 1: arrays must be of same dimension

In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])

print(var1+ var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

print(var1+ var2)

[2 4 6 8]


### Rule 2: Start comparing from right side
### Atleast one of the arrays must contain a "1" or both must be same
### The new matrix will be of size of maximum of shapes of both

In [4]:
x = np.array([1,2,3])
y = np.array([[1],[2],[3]])

print(x)
print(y)
print(x.shape)
print(y.shape)

z = x+y
print(z)
print(z.shape)

[1 2 3]
[[1]
 [2]
 [3]]
(3,)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]
(3, 3)
