### copy() -> creates a deep copy
### view() -> creates a shallow copy

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
co = arr1.copy()

co[1] = 45

print(arr1)
print(co)

[1 2 3 4 5]
[ 1 45  3  4  5]


In [4]:
arr2 = np.array([1,2,3,4,5])
vi = arr2.view()

vi[1] = 45

print(arr2)
print(vi)

[ 1 45  3  4  5]
[ 1 45  3  4  5]
