In [1]:
import numpy as np

### The basics

In [2]:
a = np.array([1,2,3])
b = np.array([[1,2,3],
              [4,5,6]])

In [3]:
# get no. of elements
print(a.size)
print(b.size)

3
6


In [4]:
# get size in bytes of a single element
print(a.itemsize)

# get total size in bytes
print(a.nbytes)

8
24


In [5]:
# get dimension
print(a.ndim)
print(b.ndim)

1
2


### Accessing/Changing specific elements, rows, columns, etc

In [6]:
a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
# access a specific element [r, c]
print(a[1,2])

10


In [8]:
a[1,2] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 20 11 12 13 14]]


In [9]:
# access a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [10]:
# access a specific column
print(a[:,3])

[ 4 11]


In [11]:
## [startindex:endindex:stepsize]

print(a[1, 0:7:2])

[ 8 20 12 14]


##### *3-d example

In [12]:
b = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
print(b[0,1,1])
print(b[1,0,1])

4
6


### Initializing Different Types of Arrays

In [ ]:
# all 0's matrix

np.zeros((2,3)) # (2 rows, 2 columns)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# all 1's matrix

np.ones((4,2,2)) # (4 matrices, 2 rows, 2 columns)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [19]:
# create an array filled any numbers you want

np.full((2,2),32)

array([[32, 32],
       [32, 32]])

In [20]:
# when you already have an array and want another one of identical size.

np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [21]:
# identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr = np.array([[1,2,3]])

np.repeat(arr,3,axis=0) # axis = 0 -> repeat rows

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [24]:
np.repeat(arr,3,axis=1) # # axis = 1 -> repeat columns

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [ ]:
# Q-1: create the pattern as shown in 'image1'

ans = np.ones((5,5))
print(ans)

sub = np.zeros((3,3))
sub[1,1] = 9
print(sub)

ans[1:4, 1:4] = sub
print(ans)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
# shallow copy
a = np.array([1,2,3])
b = a
print(a)
print(b)

b[1] = 5
print(b)
print(a)

[1 2 3]
[1 2 3]
[1 5 3]
[1 5 3]


In [35]:
# deep copy
a = np.array([1,2,3])
b = a.copy()
print(a)
print(b)

b[1] = 5
print(b)
print(a)

[1 2 3]
[1 2 3]
[1 5 3]
[1 2 3]


### Mathematics: https://docs.scipy.org/doc/numpy/reference/routines.math.html

### Linear Algebra: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html