In [1]:
import numpy as np

### Join array

#### np.concatenate() --> Joins arrays along an existing axis.

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2), axis=0) # join along y-axis , default
arr_new = np.concatenate((arr1,arr2), axis=1) # join along x-axis

print(arr)
print()
print(arr_new)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


#### np.stack() --> Joins arrays along a new axis.

In [10]:
arr = np.stack((arr1, arr2), axis=0)
arr_new = np.stack((arr1, arr2), axis=1)

print(arr)
print()
print(arr_new)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### split arrays

In [14]:
arr = np.array([1,2,3,4,5,6,])

result = np.array_split(arr, 4)
result_1 = np.array_split(arr, 3)

print(result)
print(result_1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
