In [1]:
import numpy as np

In [2]:
mat1 = np.matrix([[1, 2, 3], [4, 5, 6]])
mat2 = np.matrix([[10, 11], [12, 13], [14, 15]])

print(mat1)
print(mat1.shape)
print()
print(mat2)
print(mat2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[10 11]
 [12 13]
 [14 15]]
(3, 2)


In [4]:
print(mat1*mat2)
print()
print(mat1.dot(mat2))

[[ 76  82]
 [184 199]]

[[ 76  82]
 [184 199]]


### Matrix Functions

In [5]:
# Transpose

mat = np.matrix([[1,2,3],[4,5,6]])

print(mat)
print()
print(np.transpose(mat))
print()
print(mat.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [6]:
# Inverse

a = [[1,2],[3,4]]

print(a)
print()
print(np.linalg.inv(a))

[[1, 2], [3, 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
# Determinant

b = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(b)
print()
print(np.linalg.det(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

0.0
